### ISSUE TITLE
ReadMe instructions - Need to add quotes around $(pwd) to work for paths with spaces

### ISSUE THREAD

**Issue by jlott1** [tarvaina/tensorflow-tutorial#3]
I am very new to docker and not that savvy on Terminal on Mac.

This tutorial was very helpful for getting started, but I had one issue when trying to follow the instructions.

I kept getting an error that was completely cryptic 

`docker: invalid reference format: repository name must be lowercase.`

after google searching and scratching my head for a while.  I figured it had something to do with the path.  When I originally ran this project, I had installed this at the root directory and it ran fine, then when I moved this project folder to my desktop, I was getting this error.

so by changing slightly the commands, I was able to get it to load properly.

```
docker run \
    --name jupyter \
    -d \
    -v '$(pwd)/notebooks:/root/notebooks' \
    -v '$(pwd)/logs:/root/logs' \
    -p 8888:8888 \
    b.gcr.io/tensorflow/tensorflow \
    /run_jupyter.sh /root/notebooks
```

AND

```
docker run \
   --name tensorboard \
   -d \
   -v '$(pwd)/logs:/root/logs' \
   -p 6006:6006 \
   b.gcr.io/tensorflow/tensorflow \
   tensorboard --logdir /root/logs
```

I hope this helps.  it would be great to update the ReadMe file with this change.

**Comment by tarvaina** [comment]
Thanks for pointing it out, updated.

(I think they need to be double quotes, though.)
